/**
 * Database Types for Kysely
 *
 * Type definitions that map to the PostgreSQL database schema.
 * These types are used by Kysely for type-safe query building.
 */

import type {
  ColumnType,
  Generated,
  Insertable,
  Selectable,
  Updateable,
} from 'kysely';

// =====================================================
// COLUMN TYPE HELPERS
// =====================================================

/**
 * UUID type - generated by default
 */
type UUID = Generated<string>;

/**
 * Timestamp - auto-generated on insert
 */
type CreatedAt = ColumnType<Date, Date | undefined, never>;

/**
 * Timestamp - auto-updated on modification
 */
type UpdatedAt = ColumnType<Date, Date | undefined, Date>;

/**
 * Nullable timestamp for soft deletes
 */
type DeletedAt = ColumnType<Date | null, Date | null | undefined, Date | null>;

// =====================================================
// TABLE DEFINITIONS
// =====================================================

/**
 * Users table
 */
export interface UsersTable {
  id: UUID;
  email: string;
  username: string;
  password_hash: string;
  full_name: string | null;
  bio: string | null;
  avatar_url: string | null;
  social_links: Record<string, string>;
  email_verified: ColumnType<boolean, boolean | undefined, boolean>;
  is_active: ColumnType<boolean, boolean | undefined, boolean>;
  is_admin: ColumnType<boolean, boolean | undefined, boolean>;
  spam_score: ColumnType<number, number | undefined, number>;
  // Account lockout fields
  failed_login_attempts: ColumnType<number, number | undefined, number>;
  locked_until: ColumnType<Date | null, Date | null | undefined, Date | null>;
  last_login_at: ColumnType<Date | null, Date | null | undefined, Date | null>;
  password_changed_at: ColumnType<
    Date | null,
    Date | null | undefined,
    Date | null
  >;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at: DeletedAt;
}

/**
 * Categories table
 */
export interface CategoriesTable {
  id: UUID;
  name: string;
  slug: string;
  description: string | null;
  color: ColumnType<string, string | undefined, string>;
  post_count: ColumnType<number, number | undefined, number>;
  created_at: CreatedAt;
}

/**
 * Tags table
 */
export interface TagsTable {
  id: UUID;
  name: string;
  slug: string;
  usage_count: ColumnType<number, number | undefined, number>;
  created_at: CreatedAt;
}

/**
 * Videos table
 */
export interface VideosTable {
  id: UUID;
  post_id: string | null;
  original_filename: string;
  file_size: number;
  mime_type: string;
  status: ColumnType<string, string | undefined, string>;
  duration: number | null;
  width: number | null;
  height: number | null;
  original_codec: string | null;
  original_bitrate: number | null;
  raw_file_path: string | null;
  hls_master_url: string | null;
  thumbnail_url: string | null;
  available_qualities: Record<string, unknown>[];
  retry_count: ColumnType<number, number | undefined, number>;
  error_message: string | null;
  uploaded_at: Date | null;
  processing_completed_at: Date | null;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at: DeletedAt;
}

/**
 * Posts table
 */
export interface PostsTable {
  id: UUID;
  author_id: string;
  title: string;
  slug: string;
  content: string;
  excerpt: string | null;
  featured_image_url: string | null;
  video_id: string | null;
  status: ColumnType<string, string | undefined, string>;
  visibility: ColumnType<string, string | undefined, string>;
  view_count: ColumnType<number, number | undefined, number>;
  like_count: ColumnType<number, number | undefined, number>;
  comment_count: ColumnType<number, number | undefined, number>;
  bookmark_count: ColumnType<number, number | undefined, number>;
  embedding: number[] | null;
  published_at: Date | null;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at: DeletedAt;
}

/**
 * Post Categories junction table
 */
export interface PostCategoriesTable {
  post_id: string;
  category_id: string;
}

/**
 * Post Tags junction table
 */
export interface PostTagsTable {
  post_id: string;
  tag_id: string;
}

/**
 * Comments table
 */
export interface CommentsTable {
  id: UUID;
  post_id: string;
  user_id: string;
  parent_id: string | null;
  content: string;
  is_flagged: ColumnType<boolean, boolean | undefined, boolean>;
  like_count: ColumnType<number, number | undefined, number>;
  status: ColumnType<string, string | undefined, string>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at: DeletedAt;
  deleted_by: string | null;
}

/**
 * Likes table
 */
export interface LikesTable {
  id: UUID;
  user_id: string;
  post_id: string;
  created_at: CreatedAt;
}

/**
 * Comment Likes table
 */
export interface CommentLikesTable {
  user_id: string;
  comment_id: string;
  created_at: CreatedAt;
}

/**
 * Bookmark Folders table
 */
export interface BookmarkFoldersTable {
  id: UUID;
  user_id: string;
  name: string;
  description: string | null;
  color: string | null;
  sort_order: ColumnType<number, number | undefined, number>;
  is_default: ColumnType<boolean, boolean | undefined, boolean>;
  bookmark_count: ColumnType<number, number | undefined, number>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/**
 * Bookmarks table
 */
export interface BookmarksTable {
  id: UUID;
  user_id: string;
  post_id: string;
  folder_id: string;
  note: string | null;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/**
 * Sessions table
 */
export interface SessionsTable {
  id: UUID;
  user_id: string;
  token: string;
  ip_address: string | null;
  user_agent: string | null;
  device_info: Record<string, unknown> | null;
  expires_at: Date;
  last_active_at: ColumnType<Date, Date | undefined, Date>;
  created_at: CreatedAt;
}

/**
 * Post Views table
 */
export interface PostViewsTable {
  id: UUID;
  post_id: string;
  session_id: string;
  user_id: string | null;
  referrer: string | null;
  user_agent: string | null;
  is_bot: ColumnType<boolean, boolean | undefined, boolean>;
  viewed_at: ColumnType<Date, Date | undefined, never>;
  view_date: Date; // Generated column
}

/**
 * Video Views table
 */
export interface VideoViewsTable {
  id: UUID;
  video_id: string;
  session_id: string;
  user_id: string | null;
  duration_watched: number;
  total_duration: number;
  completion_rate: number; // Generated column
  quality_watched: string | null;
  referrer: string | null;
  viewed_at: ColumnType<Date, Date | undefined, never>;
}

/**
 * Activity Logs table
 */
export interface ActivityLogsTable {
  id: UUID;
  actor_id: string;
  action: string;
  target_type: string;
  target_id: string;
  metadata: Record<string, unknown> | null;
  created_at: CreatedAt;
}

/**
 * Search Queries table
 */
export interface SearchQueriesTable {
  id: UUID;
  user_id: string | null;
  query: string;
  search_type: string;
  results_count: number | null;
  created_at: CreatedAt;
}

/**
 * Follows table
 */
export interface FollowsTable {
  id: UUID;
  follower_id: string;
  following_id: string;
  created_at: CreatedAt;
}

// =====================================================
// DATABASE SCHEMA
// =====================================================

/**
 * Complete database schema for Kysely
 */
export interface Database {
  users: UsersTable;
  categories: CategoriesTable;
  tags: TagsTable;
  videos: VideosTable;
  posts: PostsTable;
  post_categories: PostCategoriesTable;
  post_tags: PostTagsTable;
  comments: CommentsTable;
  likes: LikesTable;
  comment_likes: CommentLikesTable;
  bookmark_folders: BookmarkFoldersTable;
  bookmarks: BookmarksTable;
  sessions: SessionsTable;
  post_views: PostViewsTable;
  video_views: VideoViewsTable;
  activity_logs: ActivityLogsTable;
  search_queries: SearchQueriesTable;
  follows: FollowsTable;
}

// =====================================================
// HELPER TYPES FOR CRUD OPERATIONS
// =====================================================

// Users
export type UserRow = Selectable<UsersTable>;
export type NewUser = Insertable<UsersTable>;
export type UserUpdate = Updateable<UsersTable>;

// Categories
export type CategoryRow = Selectable<CategoriesTable>;
export type NewCategory = Insertable<CategoriesTable>;
export type CategoryUpdate = Updateable<CategoriesTable>;

// Tags
export type TagRow = Selectable<TagsTable>;
export type NewTag = Insertable<TagsTable>;
export type TagUpdate = Updateable<TagsTable>;

// Videos
export type VideoRow = Selectable<VideosTable>;
export type NewVideo = Insertable<VideosTable>;
export type VideoUpdate = Updateable<VideosTable>;

// Posts
export type PostRow = Selectable<PostsTable>;
export type NewPost = Insertable<PostsTable>;
export type PostUpdate = Updateable<PostsTable>;

// Comments
export type CommentRow = Selectable<CommentsTable>;
export type NewComment = Insertable<CommentsTable>;
export type CommentUpdate = Updateable<CommentsTable>;

// Likes
export type LikeRow = Selectable<LikesTable>;
export type NewLike = Insertable<LikesTable>;

// Comment Likes
export type CommentLikeRow = Selectable<CommentLikesTable>;
export type NewCommentLike = Insertable<CommentLikesTable>;

// Bookmark Folders
export type BookmarkFolderRow = Selectable<BookmarkFoldersTable>;
export type NewBookmarkFolder = Insertable<BookmarkFoldersTable>;
export type BookmarkFolderUpdate = Updateable<BookmarkFoldersTable>;

// Bookmarks
export type BookmarkRow = Selectable<BookmarksTable>;
export type NewBookmark = Insertable<BookmarksTable>;
export type BookmarkUpdate = Updateable<BookmarksTable>;

// Sessions
export type SessionRow = Selectable<SessionsTable>;
export type NewSession = Insertable<SessionsTable>;
export type SessionUpdate = Updateable<SessionsTable>;

// Activity Logs
export type ActivityLogRow = Selectable<ActivityLogsTable>;
export type NewActivityLog = Insertable<ActivityLogsTable>;

// Follows
export type FollowRow = Selectable<FollowsTable>;
export type NewFollow = Insertable<FollowsTable>;
